pipeline {
    agent {
        label 'jenkins-jenkins-agent'
    }
    stages {
        stage('Checkout from SCM'){
            steps {
                git branch: 'task-6', url: 'https://github.com/kitakiv/rsschool-devops-course-tasks/'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}