apiVersion: v1
kind: Pod
spec:
  restartPolicy: Never
  containers:
  - name: kubectl
    image: alpine/helm:3.14.0
    command:
      - cat
    tty: true
    volumeMounts:
      - name: kubeconfig-volume
        mountPath: /root/.kube
        readOnly: false
  volumes:
    - name: kubeconfig-volume
      secret:
        secretName: kubeconfig-secret
