apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sonar-agent
spec:
  containers:
    - name: sonar-scanner
      image: sonarsource/sonar-scanner-cli:latest
      command:
        - cat
      tty: true