apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage-pvc
  namespace: jenkins-helm
spec:
  volumeName: local-storage-pv
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi