pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: python
      image: python:3
      command:
        - cat
      tty: true
      workingDir: /home/jenkins/agent
"""
        }
    }
    stages {
        stage('Clean workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout from SCM'){
            steps {
                git branch: 'task-6', url: 'https://github.com/kitakiv/rsschool-devops-course-tasks/'
            }
        }
        stage('Build') {
            steps {
                sh 'pip install -r ./python_app/requirements.txt'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}