apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage-pvc # replace with your name
  namespace: jenkins-helm
spec:
  volumeName: local-storage-pv # replace with your PV name
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi