grafana:
  service:
    type: NodePort
    nodePort: 30000
    port: 80
  admin:
    existingSecret: "grafana-admin-secret"
    userKey: admin-user
    passwordKey: admin-password
  serviceMonitor:
    enabled: true

prometheus:
  service:
    type: NodePort
    nodePort: 30090
    port: 9090

alertmanager:
  service:
    type: NodePort
    nodePort: 30095
    port: 9093

prometheusOperator:
  admissionWebhooks:
    enabled: false

prometheus:
  prometheusSpec:
    scrapeInterval: 15s