apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: monitoring-helm
data:
  alert-rules.yaml: |
    groups:
      - name: node.rules
        rules:
          - alert: HighCPUUsage
            expr: 100 - (avg by(instance)(irate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 90
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage on {{ $labels.instance }}"
              description: "CPU usage is above 90% for more than 2 minutes."

          - alert: LowRAMAvailable
            expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "Low available RAM on {{ $labels.instance }}"
              description: "Available memory is less than 10% for more than 2 minutes."