apiVersion: v1
kind: Secret
metadata:
  name: scrape-configs
  namespace: monitoring-helm
type: Opaque
stringData:
  prometheus-additional.yaml: |
    - job_name: 'flask-app'
      metrics_path: /metrics
      static_configs:
        - targets:
            - python-app-flask-project.flask-helm.svc.cluster.local:80