grafana:
  admin:
    existingSecret: "grafana-admin-secret"
    userKey: "user"
    passwordKey: "password"
  service:
    type: NodePort
    port: 80
    nodePort: 31000

prometheus:
  prometheusSpec:
    scrapeInterval: "15s"
    retention: "10d"
  service:
    type: NodePort
    nodePort: 32090

alertmanager:
  alertmanagerSpec:
    replicas: 2
    retention: "120h"
  service:
    type: NodePort
    nodePort: 32093

