{
 "title": "Test Flask Dashboard",
 "panels": [
  {
   "title": "CPU Usage (seconds)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Memory Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Resident Memory" }
   ]
  },
  {
   "title": "Disk Usage (Virtual Memory)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "Virtual Memory" }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(flask_app_requests_total[5m])",
     "legendFormat": "HTTP requests"
    }
   ]
  },
  {
   "title": "Avg Request Duration (seconds)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "rate(flask_app_request_duration_seconds_sum[5m]) / rate(flask_app_request_duration_seconds_count[5m])",
     "legendFormat": "Latency"
    }
   ]
  }
 ]
}